CREATE TABLE MEMBER(
	MEMBER_ID VARCHAR2(50),
	MEMBER_PASSWORD VARCHAR2(50) NOT NULL,
	MEMBER_NAME VARCHAR2(20) NOT NULL,
	MEMBER_POWER NUMBER(2) NOT NULL,
	MEMBER_POINT NUMBER NOT NULL DEFAULT 0,
	MEMBER_ACT NUMBER DEFAULT 0 NOT NULL,
	PRIMARY KEY(MEMBER_ID)
);

CREATE TABLE PROFILE(
	MEMBER_ID VARCHAR2(50),
	PROFILE_TECH VARCHAR2(30),
	PROFILE_BLOG VARCHAR2(30),
	PROFILE_JOB VARCHAR2(40),
	PROFILE_PAY VARCHAR2(10),
	PROFILE_NAME VARCHAR2(10),
	PROFILE_EMAIL VARCHAR2(20),
	PROFILE_PHONE VARCHAR2(20),
	PROFILE_INTRO VARCHAR2(300),
	PROFILE_YEAR VARCHAR2(10),
	PROFILE_STRENGTH VARCHAR2(100),
	PRIMARY KEY(MEMBER_ID),
	FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE
);

CREATE TABLE EDU(
	EDU_ID NUMBER,
	MEMBER_ID VARCHAR2(50) NOT NULL,
	EDU_NAME VARCHAR2(20) NOT NULL,
	EDU_MAJOR VARCHAR2(20) NOT NULL,
	EDU_DEGREE VARCHAR2(20) NOT NULL,
	EDU_START DATE NOT NULL,
	EDU_END DATE NOT NULL,
	EDU_GRADE VARCHAR2(10),
	EDU_GRADE_MAX VARCHAR2(10),
	EDU_ETC VARCHAR2(100),
	PRIMARY KEY(EDU_ID),
	FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE
)

CREATE SEQUENCE EDU_SEQ;

