DROP TABLE MEMBER CASCADE CONSTRAINTS;

DROP TABLE PROFILE CASCADE CONSTRAINTS;

DROP TABLE EDU CASCADE CONSTRAINTS;
DROP SEQUENCE EDU_SEQ;

DROP TABLE AWARD_LICENSE CASCADE CONSTRAINTS;
DROP SEQUENCE AWARD_LICENSE_SEQ;

DROP TABLE PORTFOLIO CASCADE CONSTRAINTS;
DROP SEQUENCE PORTFOLIO_SEQ;

DROP TABLE FOREIGN CASCADE CONSTRAINTS;
DROP SEQUENCE FOREIGN_SEQ;

DROP TABLE PORT_RECOMMEND CASCADE CONSTRAINTS;
DROP SEQUENCE PORT_RECOMMEND_SEQ;

DROP TABLE PORT_FEEDBACK CASCADE CONSTRAINTS;
DROP SEQUENCE PORT_FEEDBACK_SEQ;

DROP TABLE PORT_FEEDBACK_RECOMMEND CASCADE CONSTRAINTS;
DROP SEQUENCE PORT_FEEDBACK_RECOMMEND_SEQ;

DROP TABLE PORT_SCRAP CASCADE CONSTRAINTS;
DROP SEQUENCE PORT_SCRAP_SEQ;

DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP SEQUENCE BOARD_SEQ;

DROP TABLE BOARD_COMMENT CASCADE CONSTRAINTS;
DROP SEQUENCE BOARD_COMMENT_SEQ;

DROP TABLE BAD_REPORT CASCADE CONSTRAINTS;
DROP SEQUENCE BAD_REPORT_SEQ;

DROP TABLE BOARD_FILE CASCADE CONSTRAINTS;
DROP SEQUENCE BOARD_FILE_SEQ;

DROP TABLE ACTIVE CASCADE CONSTRAINTS;
DROP SEQUENCE ACTIVE_SEQ;

DROP TABLE BOARD_RECOMMEND CASCADE CONSTRAINTS;
DROP SEQUENCE BOARD_RECO_ID;

DROP TABLE MEMBER_LOG CASCADE CONSTRAINTS;
DROP SEQUENCE MEMBER_LOG_SEQ;

DROP TABLE ALERT CASCADE CONSTRAINTS;
DROP SEQUENCE ALERT_SEQ;